[package]

name = "graph"
version = "0.0.1"
authors = ["David Edmonds <edmonds.d.r@gmail.com>"]

[dependencies.glium]
git = "https://github.com/tomaka/glium"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
