[package]

name = "graph"
version = "0.0.1"
authors = ["David Edmonds <edmonds.d.r@gmail.com>"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
